import express from 'express';
import EnvironmentalFile from '../models/EnvironmentalFile.js';
import { authenticateToken } from '../middleware/auth.js';

const router = express.Router();

// Create Environmental File
router.post('/', authenticateToken, async (req, res) => {
  try {
    const fileData = req.body;
    // id should be unique, generated by frontend or backend
    if (!fileData.id) {
      return res.status(400).json({ error: 'Missing file id' });
    }
    const newFile = new EnvironmentalFile({
      ...fileData,
      userId: req.userId
    });
    await newFile.save();
    res.status(201).json(newFile);
  } catch (err) {
    console.error('Error creating environmental file:', err);
    if (err.name === 'ValidationError') {
      return res.status(400).json({
        error: 'Validation error',
        details: err.message,
        fields: Object.keys(err.errors || {})
      });
    }
    res.status(500).json({ error: err.message });
  }
});

// Get All Environmental Files
router.get('/', authenticateToken, async (req, res) => {
  try {
    const files = await EnvironmentalFile.find({ userId: req.userId });
    res.json(files);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Update Environmental File
router.put('/:id', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const updatedFile = await EnvironmentalFile.findOneAndUpdate(
      { id: id, userId: req.userId },
      req.body,
      { new: true, runValidators: true }
    );
    if (!updatedFile) {
      return res.status(404).json({ error: 'File not found' });
    }
    res.json(updatedFile);
  } catch (err) {
    console.error('Error updating environmental file:', err);
    if (err.name === 'ValidationError') {
      return res.status(400).json({
        error: 'Validation error',
        details: err.message,
        fields: Object.keys(err.errors || {})
      });
    }
    res.status(500).json({ error: err.message });
  }
});

// Delete Environmental File
router.delete('/:id', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const deletedFile = await EnvironmentalFile.findOneAndDelete({ id: id, userId: req.userId });
    if (!deletedFile) {
      return res.status(404).json({ error: 'File not found' });
    }
    res.json({ message: 'File deleted successfully' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Move file to folder
router.put('/:id/move', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const { folderId } = req.body;

    const updatedFile = await EnvironmentalFile.findOneAndUpdate(
      { id: id, userId: req.userId },
      { folder_id: folderId || null },
      { new: true, runValidators: true }
    );

    if (!updatedFile) {
      return res.status(404).json({ error: 'File not found' });
    }

    res.json(updatedFile);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Download file as Word document
router.get('/:id/download', authenticateToken, async (req, res) => {
  try {
    const { id } = req.params;
    const file = await EnvironmentalFile.findOne({ id: id, userId: req.userId });

    if (!file) {
      return res.status(404).json({ error: 'File not found' });
    }

    // Import the document service
    const { generateDocument } = await import('../routes/documents.js');

    // Generate Word document
    const docBuffer = await generateDocument(file);

    // Set headers for file download
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="file-${id}.docx"`);
    res.setHeader('Content-Length', docBuffer.length);

    res.send(docBuffer);
  } catch (err) {
    console.error('Error downloading file:', err);
    res.status(500).json({ error: err.message });
  }
});

export default router;
